#!/bin/bash

CERTBOT_CREATE_DOMAIN=$NGINX_DOMAIN
CERTBOT_CREATE_EMAIL=$CERTBOT_EMAIL
CERTBOT_CREATE_IS_STAGING=$CERTBOT_TEST
CERTBOT_CREATE_CERT_LOC=/etc/letsencrypt/live/$CERTBOT_CREATE_DOMAIN/
CERTBOT_CREATE_CERT_FILE=${CERTBOT_CREATE_CERT_LOC}fullchain.pem
CERTBOT_CREATE_CERT_KEY=${CERTBOT_CREATE_CERT_LOC}privkey.pem
CERTBOT_CREATE_WEBROOT=/var/www/certbot

if [ ! ${CERTBOT_CREATE_IS_STAGING} = false ]; then
    CERTBOT_CREATE_STAGING=--staging
fi

#Show variables to be used
echo Using the following configs
echo DOMAIN: $CERTBOT_CREATE_DOMAIN
echo STAGING: $CERTBOT_CREATE_IS_STAGING
echo CERT_LOCATION: $CERTBOT_CREATE_CERT_LOC
echo EMAIL $CERTBOT_CREATE_EMAIL
echo STAGING_FLAG: $CERTBOT_CREATE_STAGING
echo WEBROOT: $CERTBOT_CREATE_WEBROOT

#Generate the certificate
rm -rf $CERTBOT_CREATE_CERT_LOC && \
mkdir -p $CERTBOT_CREATE_WEBROOT && \
certbot certonly \
    --webroot \
    --webroot-path=$CERTBOT_CREATE_WEBROOT \
    $CERTBOT_CREATE_STAGING \
    -d $CERTBOT_CREATE_DOMAIN \
    --agree-tos \
    -m $CERTBOT_CREATE_EMAIL && \
nginx -s reload
